### ISSUE TITLE
Gudgeon may not be edible

### ISSUE THREAD

**Issue by RenegadeElement** [Amostubal/modified-MWDF#14]
It may be missing the edibility tags.

**Comment by Amostubal** [comment]
there is no edibility tags on fish, aquatic life are all either vermin(which means they can be caught by fishing and cleaned) or they are not vermin (which means they are big enough to try and get out of water and attack you and therefore need to be butchered).

**Comment by RenegadeElement** [comment]
even the cleaned version is missing the tag. I had made a meal that was 2 minced rainbow and 1 gudgeon. i check the fish and only the rainbow fillets in that stockpile said they were edible. raw or cooked. The gudgeon got cooked But i don't think it ever got eaten.

**Comment by Amostubal** [comment]
http://image.prntscr.com/image/cf2a3cefcf314a0d9bc9adbed1863c75.png

Gudgeon being eaten.

I just made an embark 0 food stock, generated a thousand raw gudgeons and set up some shops, they can be cooked, and they do get eaten in meals, cleaned, and even raw (the last thing they will try but they got to get really hungry first).
