### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RenegadeElement** [Amostubal/modified-MWDF#15]
Attempted to type cherry into the the workshop material conditions for a job order for I think a chair. Saving the entire instance this time. Where do you want the files?(pm me)

**Comment by Amostubal** [comment]
just upload them to DFFD.bay12games.com it will take just about anything, and has a category for crashing games, send me a link to it.

**Comment by RenegadeElement** [comment]
I don't have a forum account
And for reasons I don't want to go into I don't want one.
oh if you want to talk privately I am on discord at https://discord.gg/PsE7ytR

**Comment by Amostubal** [comment]
looked at the save and couldn't find anything wrong nor repeat the error.  must of been a random oddity.
