### ISSUE TITLE
liquid or liquids?

### ISSUE THREAD

**Issue by tali713** [Amostubal/modified-MWDF#23]
In [raw/onLoad.init](https://github.com/Amostubal/modified-MWDF/blob/77944c0479741ec3f4cf86f7b1881d31d28ee1d8/MWDF%20Project/Dwarf%20Fortress/raw/onLoad.init#L25) you run base/liquid-update, however the script in [hack/base/masterwork/](https://github.com/Amostubal/modified-MWDF/tree/77944c0479741ec3f4cf86f7b1881d31d28ee1d8/MWDF%20Project/Dwarf%20Fortress/hack/scripts/masterwork/base) is named liquids-update.lua.  This generates an error on world load that is easy to overlook.

**Comment by Amostubal** [comment]
Thanks.  I didn't see that.  Not sure if that effects anything. Maybe succubus specialty shops.

**Comment by Amostubal** [comment]
actually it can be completely removed. the roses-init command now calls all of updaters on its own... so it wasn't a problem that I failed the call to begin with.  thanks for the catch... It makes me feel better knowing people are keeping me on my toes! lol
