### ISSUE TITLE
Default Succubus sprites incorrectly located

### ISSUE THREAD

**Issue by tali713** [Amostubal/modified-MWDF#41]
See: Devduweb/DF-succubus#62

**Comment by tali713** [comment]
I can submit a pull request here if we don't mind skipping ahead of the base mod.

**Comment by Amostubal** [comment]
I try not to step on boltguns toes to much.  But any correction we make in MDF is preferred over his until he submits a working correction.

**Comment by Amostubal** [comment]
Is it ready? or do we need to move this idea to the next version?

**Comment by tali713** [comment]
Pull request made on that branch.

**Comment by Amostubal** [comment]
closing since its added over on 1.28
